### ISSUE TITLE
Sunrise/Sunset calculation hangs for a specific Date/lat/long combo

### ISSUE THREAD

**Issue by cracell** [varvet/sun_time#1]
The calculations for 

suntime = SunTime.new(Date.parse("2011-07-21"), 34.2578, -118.757)
suntime.sunrise #Hangs and does not complete
suntime.sunset #hangs and does not complete

Other dates for that latitude/longitude work correctly.

**Comment by cjse** [comment]
Thanks, I'll look into it.

**Comment by cracell** [comment]
Did some research on this today. 

It looks like it's getting stuck in the "def recalculate_m" (sun_time.rb line 97) loop. I don't really understand what's going on to calculate this and why it's getting stuck here for this particular combo though.

**Comment by cracell** [comment]
I couldn't figure out how to patch this so I ended up making a new gem https://github.com/cracell/when_sun based on this one https://github.com/joeyates/ruby-sun-times with a few patches/changes to make it a proper gem.

**Comment by nowells** [comment]
@cracell looks like this has been addressed in pull request #4

**Comment by cjse** [comment]
I've merged pull request 4, that @beerlington was nice enough to provide. Should fix the issue. I'll try to release a new gem version next week.

**Comment by beerlington** [comment]
@cjkihlbom Was curious if you're still planning on releasing a new gem this week.
